using System.Data;
using System.Data.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Government_Service_Navigator.Backend.Data.Context;
using System.ComponentModel.DataAnnotations;

namespace Government_Service_Navigator.Backend.Controllers
{
    [ApiController]
    [Route("api/admin/collection-slots")]
    [Authorize(Roles = "Admin,System Admin")]
    public class CollectionSlotsController : ControllerBase
    {
        private readonly AppDbContext _context;

        public CollectionSlotsController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> GetAllSlots()
        {
            var slots = new List<CollectionTimeSlot>();
            var conn = _context.Database.GetDbConnection();
            bool wasClosed = conn.State == ConnectionState.Closed;
            
            try
            {
                if (wasClosed) await conn.OpenAsync();
                using var cmd = conn.CreateCommand();

                // 1. FAIL-SAFE: Guarantee the tables exist before trying to read from them
                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS ""CollectionTimeSlots"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""DayOfWeek"" integer NOT NULL CHECK (""DayOfWeek"" >= 1 AND ""DayOfWeek"" <= 6),
                        ""StartTime"" time NOT NULL,
                        ""EndTime"" time NOT NULL,
                        ""MaxCapacity"" integer NOT NULL DEFAULT 5,
                        ""IsActive"" boolean NOT NULL DEFAULT TRUE
                    );
                    CREATE TABLE IF NOT EXISTS ""CollectionBookings"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""ApplicationId"" integer NOT NULL,
                        ""CitizenNic"" text NOT NULL,
                        ""CollectionMethod"" text NOT NULL,
                        ""PreferredTimes"" text NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                    );
                ";
                await cmd.ExecuteNonQueryAsync();

                // 2. READ DATA: Use CAST AS varchar to completely bypass Npgsql TimeOnly/TimeSpan mapping crashes
                cmd.CommandText = "SELECT \"Id\", \"DayOfWeek\", CAST(\"StartTime\" AS varchar), CAST(\"EndTime\" AS varchar), \"MaxCapacity\", \"IsActive\" FROM \"CollectionTimeSlots\" ORDER BY \"DayOfWeek\", \"StartTime\"";
                
                using var reader = await cmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    slots.Add(new CollectionTimeSlot
                    {
                        Id = reader.GetInt32(0),
                        DayOfWeek = reader.GetInt32(1),
                        StartTime = reader.GetString(2),
                        EndTime = reader.GetString(3),
                        MaxCapacity = reader.GetInt32(4),
                        IsActive = reader.GetBoolean(5)
                    });
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Database Error: {ex.Message}");
            }
            finally
            {
                if (wasClosed) await conn.CloseAsync();
            }

            return Ok(slots);
        }

        [HttpPost]
        public async Task<IActionResult> CreateSlot([FromBody] CollectionTimeSlotDto dto)
        {
            if (dto.DayOfWeek < 1 || dto.DayOfWeek > 6)
                return BadRequest("DayOfWeek must be between 1 (Monday) and 6 (Saturday). Sundays are holidays.");

            // ::time safely casts the string payload directly into a PostgreSQL time object
            var sql = "INSERT INTO \"CollectionTimeSlots\" (\"DayOfWeek\", \"StartTime\", \"EndTime\", \"MaxCapacity\", \"IsActive\") VALUES ({0}, {1}::time, {2}::time, {3}, {4})";
            await _context.Database.ExecuteSqlRawAsync(sql, dto.DayOfWeek, dto.StartTime, dto.EndTime, dto.MaxCapacity, dto.IsActive);
            
            return Ok(new { message = "Time slot created successfully." });
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateSlot(int id, [FromBody] CollectionTimeSlotDto dto)
        {
            if (dto.DayOfWeek < 1 || dto.DayOfWeek > 6)
                return BadRequest("DayOfWeek must be between 1 (Monday) and 6 (Saturday). Sundays are holidays.");

            var sql = "UPDATE \"CollectionTimeSlots\" SET \"DayOfWeek\" = {0}, \"StartTime\" = {1}::time, \"EndTime\" = {2}::time, \"MaxCapacity\" = {3}, \"IsActive\" = {4} WHERE \"Id\" = {5}";
            await _context.Database.ExecuteSqlRawAsync(sql, dto.DayOfWeek, dto.StartTime, dto.EndTime, dto.MaxCapacity, dto.IsActive, id);
            
            return Ok(new { message = "Time slot updated." });
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSlot(int id)
        {
            var sql = "DELETE FROM \"CollectionTimeSlots\" WHERE \"Id\" = {0}";
            await _context.Database.ExecuteSqlRawAsync(sql, id);
            return Ok(new { message = "Time slot deleted." });
        }
    }

    public class CollectionTimeSlot
    {
        public int Id { get; set; }
        public int DayOfWeek { get; set; }
        public string? StartTime { get; set; }
        public string? EndTime { get; set; }
        public int MaxCapacity { get; set; }
        public bool IsActive { get; set; }
    }

    public class CollectionTimeSlotDto
    {
        [Range(1, 6)]
        public int DayOfWeek { get; set; }
        public string? StartTime { get; set; }
        public string? EndTime { get; set; }
        public int MaxCapacity { get; set; } = 5;
        public bool IsActive { get; set; } = true;
    }
}
