using System.Data;
using System.Data.Common;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Government_Service_Navigator.Backend.Data.Context;
using System.ComponentModel.DataAnnotations;

namespace Government_Service_Navigator.Backend.Controllers
{
    [ApiController]
    [Route("api/admin/collection-slots")]
    [Authorize(Roles = "Admin,System Admin,Officer,SuperAdmin,Department Admin,DepartmentAdmin,Verifying Officer,Finance Officer")]
    public class CollectionSlotsController : ControllerBase
    {
        private readonly AppDbContext _context;

        public CollectionSlotsController(AppDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetAllSlots([FromQuery] string? department)
        {
            var slots = new List<CollectionTimeSlot>();
            var conn = _context.Database.GetDbConnection();
            bool wasClosed = conn.State == ConnectionState.Closed;

            try
            {
                if (wasClosed) await conn.OpenAsync();
                using var cmd = conn.CreateCommand();

                // 1. FAIL-SAFE: Guarantee the tables and departmental columns exist
                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS ""CollectionTimeSlots"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""DepartmentId"" integer NULL,
                        ""DepartmentName"" text NULL,
                        ""DayOfWeek"" integer NOT NULL CHECK (""DayOfWeek"" >= 1 AND ""DayOfWeek"" <= 6),
                        ""StartTime"" time NOT NULL,
                        ""EndTime"" time NOT NULL,
                        ""MaxCapacity"" integer NOT NULL DEFAULT 5,
                        ""IsActive"" boolean NOT NULL DEFAULT TRUE
                    );
                    ALTER TABLE ""CollectionTimeSlots"" ADD COLUMN IF NOT EXISTS ""DepartmentId"" integer NULL;
                    ALTER TABLE ""CollectionTimeSlots"" ADD COLUMN IF NOT EXISTS ""DepartmentName"" text NULL;

                    CREATE TABLE IF NOT EXISTS ""CollectionBookings"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""ApplicationId"" integer NOT NULL DEFAULT 0,
                        ""CitizenNic"" text NOT NULL,
                        ""CollectionMethod"" text NOT NULL,
                        ""PreferredTimes"" text NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        ""ApplicationCode"" text NULL,
                        ""DepartmentName"" text NULL,
                        ""ServiceName"" text NULL,
                        ""BookedDate"" date NULL,
                        ""BookedSlotTime"" text NULL,
                        ""Status"" text NOT NULL DEFAULT 'Confirmed',
                        ""ConfirmationCode"" text NULL,
                        ""AgentNotes"" text NULL
                    );
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""ApplicationCode"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""DepartmentName"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""ServiceName"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""BookedDate"" date NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""BookedSlotTime"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""Status"" text NOT NULL DEFAULT 'Confirmed';
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""ConfirmationCode"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""AgentNotes"" text NULL;
                ";
                await cmd.ExecuteNonQueryAsync();

                // 2. Auto-seed departmental slots if table has no department-scoped slots yet
                await EnsureDepartmentSlotsSeededAsync(conn);

                // 3. READ DATA: Scoped by department if requested, plus calculating live BookedCount
                using var queryCmd = conn.CreateCommand();
                if (!string.IsNullOrWhiteSpace(department))
                {
                    queryCmd.CommandText = @"
                        SELECT s.""Id"", s.""DayOfWeek"", CAST(s.""StartTime"" AS varchar), CAST(s.""EndTime"" AS varchar), 
                               s.""MaxCapacity"", s.""IsActive"", COALESCE(s.""DepartmentName"", 'General'), s.""DepartmentId"",
                               COALESCE((
                                   SELECT COUNT(*)::int FROM ""CollectionBookings"" b 
                                   WHERE LOWER(b.""DepartmentName"") LIKE LOWER('%' || s.""DepartmentName"" || '%')
                                     AND b.""Status"" = 'Confirmed'
                                     AND b.""BookedSlotTime"" LIKE '%' || SUBSTRING(CAST(s.""StartTime"" AS varchar) FROM 1 FOR 5) || '%'
                               ), 0) AS ""BookedCount""
                        FROM ""CollectionTimeSlots"" s
                        WHERE LOWER(s.""DepartmentName"") LIKE LOWER(@dept)
                        ORDER BY s.""DayOfWeek"", s.""StartTime"";
                    ";
                    var p = queryCmd.CreateParameter();
                    p.ParameterName = "@dept";
                    p.Value = $"%{department.Trim()}%";
                    queryCmd.Parameters.Add(p);
                }
                else
                {
                    queryCmd.CommandText = @"
                        SELECT s.""Id"", s.""DayOfWeek"", CAST(s.""StartTime"" AS varchar), CAST(s.""EndTime"" AS varchar), 
                               s.""MaxCapacity"", s.""IsActive"", COALESCE(s.""DepartmentName"", 'General'), s.""DepartmentId"",
                               COALESCE((
                                   SELECT COUNT(*)::int FROM ""CollectionBookings"" b 
                                   WHERE LOWER(b.""DepartmentName"") LIKE LOWER('%' || COALESCE(s.""DepartmentName"", '') || '%')
                                     AND b.""Status"" = 'Confirmed'
                                     AND b.""BookedSlotTime"" LIKE '%' || SUBSTRING(CAST(s.""StartTime"" AS varchar) FROM 1 FOR 5) || '%'
                               ), 0) AS ""BookedCount""
                        FROM ""CollectionTimeSlots"" s
                        ORDER BY COALESCE(s.""DepartmentName"", 'General'), s.""DayOfWeek"", s.""StartTime"";
                    ";
                }

                using var reader = await queryCmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    slots.Add(new CollectionTimeSlot
                    {
                        Id = reader.GetInt32(0),
                        DayOfWeek = reader.GetInt32(1),
                        StartTime = reader.GetString(2),
                        EndTime = reader.GetString(3),
                        MaxCapacity = reader.GetInt32(4),
                        IsActive = reader.GetBoolean(5),
                        DepartmentName = reader.GetString(6),
                        DepartmentId = reader.IsDBNull(7) ? null : reader.GetInt32(7),
                        BookedCount = reader.GetInt32(8)
                    });
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Database Error: {ex.Message}");
            }
            finally
            {
                if (wasClosed) await conn.CloseAsync();
            }

            return Ok(slots);
        }

        private static async Task EnsureDepartmentSlotsSeededAsync(DbConnection conn)
        {
            using var countCmd = conn.CreateCommand();
            countCmd.CommandText = "SELECT COUNT(*) FROM \"CollectionTimeSlots\" WHERE \"DepartmentName\" IS NOT NULL";
            var countObj = await countCmd.ExecuteScalarAsync();
            int count = Convert.ToInt32(countObj);
            if (count > 0) return;

            // Seed unique schedules for each government department
            using var insertCmd = conn.CreateCommand();
            insertCmd.CommandText = @"
                -- 1. Department of Immigration & Emigration (Battaramulla HQ)
                -- Mon-Fri: 09:00 - 11:30 (Cap 15), 13:00 - 15:30 (Cap 15)
                INSERT INTO ""CollectionTimeSlots"" (""DayOfWeek"", ""StartTime"", ""EndTime"", ""MaxCapacity"", ""IsActive"", ""DepartmentName"")
                VALUES 
                    (1, '09:00:00'::time, '11:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (1, '13:00:00'::time, '15:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (2, '09:00:00'::time, '11:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (2, '13:00:00'::time, '15:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (3, '09:00:00'::time, '11:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (3, '13:00:00'::time, '15:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (4, '09:00:00'::time, '11:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (4, '13:00:00'::time, '15:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (5, '09:00:00'::time, '11:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration'),
                    (5, '13:00:00'::time, '15:30:00'::time, 15, TRUE, 'Department of Immigration & Emigration');

                -- 2. Department of Motor Traffic (Werahera)
                -- Mon-Fri: 08:30 - 11:00 (Cap 10), 11:30 - 14:00 (Cap 10), 14:30 - 16:30 (Cap 8); Sat: 09:00 - 12:00 (Cap 12)
                INSERT INTO ""CollectionTimeSlots"" (""DayOfWeek"", ""StartTime"", ""EndTime"", ""MaxCapacity"", ""IsActive"", ""DepartmentName"")
                VALUES 
                    (1, '08:30:00'::time, '11:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (1, '11:30:00'::time, '14:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (1, '14:30:00'::time, '16:30:00'::time, 8,  TRUE, 'Department of Motor Traffic'),
                    (2, '08:30:00'::time, '11:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (2, '11:30:00'::time, '14:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (3, '08:30:00'::time, '11:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (3, '11:30:00'::time, '14:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (4, '08:30:00'::time, '11:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (4, '11:30:00'::time, '14:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (5, '08:30:00'::time, '11:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (5, '11:30:00'::time, '14:00:00'::time, 10, TRUE, 'Department of Motor Traffic'),
                    (6, '09:00:00'::time, '12:00:00'::time, 12, TRUE, 'Department of Motor Traffic');

                -- 3. Department of Registration of Persons (Suhurupaya)
                -- Mon-Fri: 09:00 - 12:00 (Cap 20), 13:00 - 15:00 (Cap 20)
                INSERT INTO ""CollectionTimeSlots"" (""DayOfWeek"", ""StartTime"", ""EndTime"", ""MaxCapacity"", ""IsActive"", ""DepartmentName"")
                VALUES 
                    (1, '09:00:00'::time, '12:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (1, '13:00:00'::time, '15:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (2, '09:00:00'::time, '12:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (2, '13:00:00'::time, '15:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (3, '09:00:00'::time, '12:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (3, '13:00:00'::time, '15:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (4, '09:00:00'::time, '12:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (4, '13:00:00'::time, '15:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (5, '09:00:00'::time, '12:00:00'::time, 20, TRUE, 'Department of Registration of Persons'),
                    (5, '13:00:00'::time, '15:00:00'::time, 20, TRUE, 'Department of Registration of Persons');

                -- 4. Police Department
                INSERT INTO ""CollectionTimeSlots"" (""DayOfWeek"", ""StartTime"", ""EndTime"", ""MaxCapacity"", ""IsActive"", ""DepartmentName"")
                VALUES 
                    (1, '09:00:00'::time, '12:00:00'::time, 10, TRUE, 'Police Department'),
                    (1, '13:00:00'::time, '15:30:00'::time, 10, TRUE, 'Police Department'),
                    (2, '09:00:00'::time, '12:00:00'::time, 10, TRUE, 'Police Department'),
                    (2, '13:00:00'::time, '15:30:00'::time, 10, TRUE, 'Police Department'),
                    (3, '09:00:00'::time, '12:00:00'::time, 10, TRUE, 'Police Department'),
                    (3, '13:00:00'::time, '15:30:00'::time, 10, TRUE, 'Police Department'),
                    (4, '09:00:00'::time, '12:00:00'::time, 10, TRUE, 'Police Department'),
                    (4, '13:00:00'::time, '15:30:00'::time, 10, TRUE, 'Police Department'),
                    (5, '09:00:00'::time, '12:00:00'::time, 10, TRUE, 'Police Department'),
                    (5, '13:00:00'::time, '15:30:00'::time, 10, TRUE, 'Police Department');

                -- 5. Divisional Secretariat
                INSERT INTO ""CollectionTimeSlots"" (""DayOfWeek"", ""StartTime"", ""EndTime"", ""MaxCapacity"", ""IsActive"", ""DepartmentName"")
                VALUES 
                    (1, '09:00:00'::time, '12:00:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (1, '13:00:00'::time, '15:30:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (2, '09:00:00'::time, '12:00:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (2, '13:00:00'::time, '15:30:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (3, '09:00:00'::time, '12:00:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (3, '13:00:00'::time, '15:30:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (4, '09:00:00'::time, '12:00:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (4, '13:00:00'::time, '15:30:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (5, '09:00:00'::time, '12:00:00'::time, 25, TRUE, 'Divisional Secretariat'),
                    (5, '13:00:00'::time, '15:30:00'::time, 25, TRUE, 'Divisional Secretariat');
            ";
            await insertCmd.ExecuteNonQueryAsync();
        }

        [HttpGet("bookings")]
        [AllowAnonymous]
        public async Task<IActionResult> GetBookings([FromQuery] string? department)
        {
            var bookings = new List<object>();
            var conn = _context.Database.GetDbConnection();
            bool wasClosed = conn.State == ConnectionState.Closed;

            try
            {
                if (wasClosed) await conn.OpenAsync();
                using var cmd = conn.CreateCommand();

                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS ""CollectionBookings"" (
                        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ""ApplicationId"" integer NOT NULL DEFAULT 0,
                        ""CitizenNic"" text NOT NULL,
                        ""CollectionMethod"" text NOT NULL,
                        ""PreferredTimes"" text NULL,
                        ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        ""ApplicationCode"" text NULL,
                        ""DepartmentName"" text NULL,
                        ""ServiceName"" text NULL,
                        ""BookedDate"" date NULL,
                        ""BookedSlotTime"" text NULL,
                        ""Status"" text NOT NULL DEFAULT 'Confirmed',
                        ""ConfirmationCode"" text NULL,
                        ""AgentNotes"" text NULL
                    );
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""ApplicationCode"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""DepartmentName"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""ServiceName"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""BookedDate"" date NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""BookedSlotTime"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""Status"" text NOT NULL DEFAULT 'Confirmed';
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""ConfirmationCode"" text NULL;
                    ALTER TABLE ""CollectionBookings"" ADD COLUMN IF NOT EXISTS ""AgentNotes"" text NULL;
                ";
                await cmd.ExecuteNonQueryAsync();

                using var queryCmd = conn.CreateCommand();
                if (!string.IsNullOrWhiteSpace(department))
                {
                    queryCmd.CommandText = @"
                        SELECT ""Id"", COALESCE(""ApplicationCode"", CAST(""ApplicationId"" AS varchar)), ""CitizenNic"", 
                               COALESCE(""DepartmentName"", 'General'), COALESCE(""ServiceName"", 'Document Collection'), 
                               COALESCE(CAST(""BookedDate"" AS varchar), ''), COALESCE(""BookedSlotTime"", ''), ""Status"", 
                               COALESCE(""ConfirmationCode"", 'SL-APT-0000'), COALESCE(""PreferredTimes"", ''), ""CreatedAt""
                        FROM ""CollectionBookings""
                        WHERE LOWER(""DepartmentName"") LIKE LOWER(@dept)
                        ORDER BY ""CreatedAt"" DESC
                        LIMIT 150;
                    ";
                    var p = queryCmd.CreateParameter();
                    p.ParameterName = "@dept";
                    p.Value = $"%{department.Trim()}%";
                    queryCmd.Parameters.Add(p);
                }
                else
                {
                    queryCmd.CommandText = @"
                        SELECT ""Id"", COALESCE(""ApplicationCode"", CAST(""ApplicationId"" AS varchar)), ""CitizenNic"", 
                               COALESCE(""DepartmentName"", 'General'), COALESCE(""ServiceName"", 'Document Collection'), 
                               COALESCE(CAST(""BookedDate"" AS varchar), ''), COALESCE(""BookedSlotTime"", ''), ""Status"", 
                               COALESCE(""ConfirmationCode"", 'SL-APT-0000'), COALESCE(""PreferredTimes"", ''), ""CreatedAt""
                        FROM ""CollectionBookings""
                        ORDER BY ""CreatedAt"" DESC
                        LIMIT 150;
                    ";
                }

                using var reader = await queryCmd.ExecuteReaderAsync();
                while (await reader.ReadAsync())
                {
                    bookings.Add(new
                    {
                        id = reader.GetInt32(0),
                        applicationCode = reader.GetString(1),
                        citizenNic = reader.GetString(2),
                        departmentName = reader.GetString(3),
                        serviceName = reader.GetString(4),
                        bookedDate = reader.GetString(5),
                        bookedSlotTime = reader.GetString(6),
                        status = reader.GetString(7),
                        confirmationCode = reader.GetString(8),
                        preferredTimes = reader.GetString(9),
                        createdAt = reader.GetDateTime(10)
                    });
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Database Error: {ex.Message}");
            }
            finally
            {
                if (wasClosed) await conn.CloseAsync();
            }

            return Ok(bookings);
        }

        [HttpPost]
        public async Task<IActionResult> CreateSlot([FromBody] CollectionTimeSlotDto dto)
        {
            if (dto.DayOfWeek < 1 || dto.DayOfWeek > 6)
                return BadRequest("DayOfWeek must be between 1 (Monday) and 6 (Saturday). Sundays are holidays.");

            if (string.IsNullOrWhiteSpace(dto.DepartmentName))
                return BadRequest("DepartmentName is required for collection slots.");

            // ::time safely casts the string payload directly into a PostgreSQL time object
            var sql = @"
                INSERT INTO ""CollectionTimeSlots"" 
                (""DayOfWeek"", ""StartTime"", ""EndTime"", ""MaxCapacity"", ""IsActive"", ""DepartmentName"", ""DepartmentId"") 
                VALUES ({0}, {1}::time, {2}::time, {3}, {4}, {5}, {6});
            ";
            await _context.Database.ExecuteSqlRawAsync(sql, dto.DayOfWeek, dto.StartTime, dto.EndTime, dto.MaxCapacity, dto.IsActive, dto.DepartmentName, dto.DepartmentId);
            
            return Ok(new { message = "Time slot created successfully for " + dto.DepartmentName });
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateSlot(int id, [FromBody] CollectionTimeSlotDto dto)
        {
            if (dto.DayOfWeek < 1 || dto.DayOfWeek > 6)
                return BadRequest("DayOfWeek must be between 1 (Monday) and 6 (Saturday). Sundays are holidays.");

            var sql = @"
                UPDATE ""CollectionTimeSlots"" 
                SET ""DayOfWeek"" = {0}, ""StartTime"" = {1}::time, ""EndTime"" = {2}::time, 
                    ""MaxCapacity"" = {3}, ""IsActive"" = {4}, ""DepartmentName"" = COALESCE({5}, ""DepartmentName""), ""DepartmentId"" = {6} 
                WHERE ""Id"" = {7};
            ";
            await _context.Database.ExecuteSqlRawAsync(sql, dto.DayOfWeek, dto.StartTime, dto.EndTime, dto.MaxCapacity, dto.IsActive, dto.DepartmentName, dto.DepartmentId, id);
            
            return Ok(new { message = "Time slot updated." });
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSlot(int id)
        {
            var sql = "DELETE FROM \"CollectionTimeSlots\" WHERE \"Id\" = {0}";
            await _context.Database.ExecuteSqlRawAsync(sql, id);
            return Ok(new { message = "Time slot deleted." });
        }
    }

    public class CollectionTimeSlot
    {
        public int Id { get; set; }
        public int? DepartmentId { get; set; }
        public string? DepartmentName { get; set; }
        public int DayOfWeek { get; set; }
        public string? StartTime { get; set; }
        public string? EndTime { get; set; }
        public int MaxCapacity { get; set; }
        public int BookedCount { get; set; }
        public int RemainingCapacity => Math.Max(0, MaxCapacity - BookedCount);
        public bool IsActive { get; set; }
    }

    public class CollectionTimeSlotDto
    {
        public int? DepartmentId { get; set; }
        public string? DepartmentName { get; set; }
        [Range(1, 6)]
        public int DayOfWeek { get; set; }
        public string? StartTime { get; set; }
        public string? EndTime { get; set; }
        public int MaxCapacity { get; set; } = 5;
        public bool IsActive { get; set; } = true;
    }
}
